highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:path.html
paginate: 5
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate, jekyll-sitemap]
port: 4000
excerpt_separator: <!--more-->
safe: false
url: http://vostrilov.name
author: Sergei Vostrilov

# edit this section with your information
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Сергей Вострилов
name: Сергей Вострилов
description: Опыт семейного сайта
email: info@vostrilov.name
email_full: mailto:info@vostrilov.name
website: github.com/vostrilovname
website_full: https://github.com/vostrilovname
github: vostrilovname
twitter: vostrilovname
tel: +7 0000 000000
tel_full: tel:+70000000000
google_maps: ''
address:
postcode:
city:
country:
google_analytics:

# needed for travis-ci build
exclude: [vendor]

#custom pages
collections:
  ancestry:
    tag: 'ancestry'
    output: true
