---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _data/metadata.json
  label: Метаданные
- type: document
  path: _data/gallery.json
  label: Галерея
- type: heading
  label: Тексты
- type: directory
  path: blog
  label: Рассказы
  create: documents
  match: "**/*"
  exclude: blog.json
  new_doc_ext: app
  templates:
  - post
- type: directory
  path: friends
  label: Друзья семьи
  create: documents
  match: "**/*"
  exclude: friends.json
  new_doc_ext: app
  templates:
  - friends
- type: directory
  path: family
  label: История семьи
  create: documents
  match: "**/*"
  exclude: family.json
  templates:
  - family
- type: directory
  path: library
  label: Библиотека
  create: documents
  match: "**/*"
  exclude: library.json
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
