---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Файлы данных
- type: document
  path: _data/gallery.json
  label: Галерея
  match: "**/*"
- type: document
  path: _data/metadata.json
  label: Метаданные
  match: "**/*"
- type: heading
  label: Контент
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
